
INSERT OR IGNORE INTO posts (slug, title, section, excerpt, body_html, song, doodle, featured, status, published_at) VALUES
('moonlit-nights','moonlit nights, strangely empty','diary',
 'a note written at 2am when the house was too quiet and the moon too loud.',
 '<p>The moon was doing that thing again — hanging low and pretending it wasn''t watching. I made tea I didn''t drink.</p><p>Some nights are just for sitting with the quiet. This was one of them.</p>',
 'TV Girl — Blue Hair','moon',1,'published',datetime('now','-1 days')),
('the-corner-shop','the man at the corner shop','incident',
 'he never remembers my name but always remembers my order. today that felt like enough.',
 '<p>Two rupees short and he waved it off like it was nothing. Maybe it was. Maybe it wasn''t.</p><p>I walked home thinking about how the smallest kindnesses are the ones that stay.</p>',
 '','star',0,'published',datetime('now','-3 days')),
('letters-i-didnt-send','letters i didn''t send','short_story',
 'a drawer full of beginnings, none of them brave enough to be finished.',
 '<p>I keep them in the second drawer, under the receipts. <em>Dear you</em>, they all start. Then nothing.</p><p>Maybe some things are only true if you never send them.</p>',
 'Cigarettes After Sex — Apocalypse','heart',0,'published',datetime('now','-5 days')),
('on-being-the-loud-one','on being the loud one in a quiet room','reflection',
 'they call it too much. i''ve started calling it alive.',
 '<p>For years I tried to shrink to fit the rooms I was in. Lately I''ve stopped folding myself so small.</p><p>If that''s too much, then maybe the room was just too small.</p>',
 '','star',0,'published',datetime('now','-8 days')),
('two-am-again','2am, again','diary',
 'the hour where every thought puts on its dramatic coat and demands to be heard.',
 '<p>Everyone''s asleep and my brain picks now — always now — to rewrite conversations from 2019.</p><p>I''ll pay for this tomorrow. I always do. And yet.</p>',
 'Lana Del Rey — Video Games','moon',0,'published',datetime('now','-11 days')),
('the-last-train','the last train home','short_story',
 'she almost missed it. maybe she wanted to.',
 '<p>The platform emptied and still she stood there, watching the lights blur into the ordinary dark.</p><p>The train came. She got on. That was the whole brave thing.</p>',
 '','star',0,'published',datetime('now','-15 days'));

INSERT INTO sections (type, heading, subhead, design, data, sort_order, status) VALUES
('featured','','featured · this week','hero',
 '{"mode":"auto","postId":null,"song":"TV Girl — Blue Hair","songUrl":"https://www.youtube.com/watch?v=YQHsXMglC9A","lyrics":["moonlit nights","strangely empty","no answer, just the hum"]}',
 10,'published'),
('story_wall','the wall','','wall','{}',20,'published'),
('venting','venting place','the loud thoughts, dated','feed',
 '{"entries":[{"id":"v1","date":"2026-07-16","mood":"anxious","body_html":"<p>Sent the story to no one and refreshed my inbox anyway. The overthinker''s cardio.</p>"},{"id":"v2","date":"2026-07-12","mood":"loved","body_html":"<p>Someone quoted a line of mine back to me today. I have been floating ever since.</p>"},{"id":"v3","date":"2026-07-05","mood":"tired","body_html":"<p>Wrote nothing. Read everything. Called it research.</p>"}]}',
 30,'published'),
('quote','','','quote',
 '{"quote":"If I was the moon, would you still look for the stars?","by":"from the margins of an old notebook"}',
 40,'published'),
('books','the reading pile','the guilty, ever-growing stack','list',
 '{"items":[{"id":"b1","title":"The Bell Jar","author":"Sylvia Plath","note":"reread every winter"},{"id":"b2","title":"Norwegian Wood","author":"Haruki Murakami","note":"the ache with a soundtrack"},{"id":"b3","title":"Milk and Honey","author":"Rupi Kaur","note":"dog-eared to death"},{"id":"b4","title":"The God of Small Things","author":"Arundhati Roy","note":"sentences I''d frame"}]}',
 50,'published'),
('music','on repeat','scored to heartbreak','cards',
 '{"playlistUrl":"https://www.youtube.com/watch?v=YQHsXMglC9A","items":[{"id":"m1","title":"Blue Hair","artist":"TV Girl","url":"https://www.youtube.com/watch?v=YQHsXMglC9A"},{"id":"m2","title":"Apocalypse","artist":"Cigarettes After Sex","url":"https://www.youtube.com/watch?v=op6l1M_gWJc"},{"id":"m3","title":"Video Games","artist":"Lana Del Rey","url":"https://www.youtube.com/watch?v=cE6wxDqdOV0"}]}',
 60,'published'),
('gallery','the art wall','things i keep looking at','polaroid',
 '{"items":[{"id":"g1","img_url":"/about/flowers.webp","caption":"the ones that dry pretty"},{"id":"g2","img_url":"/about/coffee.webp","caption":"cold again"},{"id":"g3","img_url":"/about/movies.webp","caption":"watched too many times"},{"id":"g4","img_url":"/about/camera.webp","caption":"undeveloped, like most of my plans"}]}',
 70,'published');
